name: project_management
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  dart_frog: ^0.1.2
  encrypt: ^5.0.1
  mongo_dart: ^0.8.0

dev_dependencies:
  mocktail: ^0.3.0
