name: project_management
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.2.0
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
